version: "3"

services:
  test-environment:
    restart: always
    build:
      dockerfile: Dockerfile.test
      context: .
    # ports:
    #   - #configure as needed
    volumes:
      - .:/app
      - /app/node_modules
