version: "3"

services:
  test-environment:
    restart: always
    build:
      dockerfile: Dockerfile.test-debug
      context: .
    ports:
      - "4242:4242"
    volumes:
      - .:/app
      - /app/node_modules
