version: '3'

services:
  dev-environment:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      []
      # - configure whatever ports you need to run your service in production
    volumes:
      - .:/app
      - /app/node_modules
