version: '3'

services:
  debug-environment:
    restart: always
    build:
      dockerfile: Dockerfile.debug
      context: .
    ports:
      - '4242:4242'
    volumes:
      - .:/app
      - /app/node_modules
