FROM node:12.16.1
WORKDIR '/app'

# use bash for sourcing files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# ensure system up-to-date
RUN apt-get update --fix-missing
RUN apt-get install -y curl
RUN apt-get install -y build-essential libssl-dev

RUN npm i -g nodemon

COPY package.json ./

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 12.16.1

# Install nvm and use specific node version 
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash \
  && source $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default 

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN npm i &&  npm cache clean --force
COPY . .
CMD ["npm", "run", "start:dev"]
